### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by therealklanni** [azz/prettier-plugin-bash#11]
Apologies. Just wondering if this is still being worked on, or if there's an alpha or anything usable.

Thanks!

**Comment by azz** [comment]
Sorry, no. I started working on this but haven't got it anywhere near an alpha state. I'd like to get back to it someday, or I'm happy for people to contribute or take ownership if they so desire.

**Comment by therealklanni** [comment]
Thanks for the feedback. May I suggest adding a "help wanted" label (or something in the README)?

**Comment by azz** [comment]
Thanks, I threw the `help wanted` label on the open issues.
